
# Other Homebrew packages
brew anyenv
brew git
brew mas
brew ncurses
brew node
brew pcre
brew pcre2
brew postgresql
brew yarn
brew zsh
brew chezmoi

# Other Cask applications
cask arduino
cask clipy
cask cyberduck
cask docker
cask font-hackgen
cask karabiner-elements
cask mendeley-desktop
cask notion
cask onyx
cask postman
cask slack
cask google-chrome
cask oogle-japanese-ime
cask iterm2